apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentlightstreamer
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: pod-lightstreamer
        image: lightstreamer
        ports:
        - containerPort: 8080
