apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentcliente
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: pod-cliente
        image: pablorehecho/lightstreamer-cliente
        ports:
        - containerPort: 2080 
      restartPolicy: Always       
