apiVersion: v1
kind: Service
metadata:
  name: mi-load-balancer
  labels:
    component: web
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    component: web
